name: CI

on:
  pull_request:
  push:
    branches: [ main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-10.14]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout current branch (full)
      uses: actions/checkout@v2
    - name: Setup Java and Scala
      uses: olafurpg/setup-scala@v10
    - name: Setup (Linux) on ${{ matrix.os }}
      if: matrix.os == 'ubuntu-18.04'
      run: |
        curl -v -fsSL https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-2.5.0.tar.gz \
          | tar xzv -C /usr/local
        ldconfig
    - name: Setup (OS X) on ${{ matrix.os }}
      if: matrix.os == 'macos-10.14'
      run: brew install libtensorflow@2.5.0
    - name: Run tests
      run: sbt +test
