name: CI

on:
  pull_request:
  push:
    branches: [ main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.14] #[ubuntu-18.04, 
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout current branch (full)
      uses: actions/checkout@v2
    - name: Setup Java and Scala
      uses: olafurpg/setup-scala@v10
    - name: Setup (Linux)
      if: matrix.os == 'ubuntu-18.04'
      # run: |
      #     sudo apt-get update
      #     sudo apt-get install -y libatlas-base-dev
    - name: Setup (OS X)
      if: matrix.os == 'macos-10.14'
      run: |
          brew install libtensorflow
    - name: Run tests
      run: sbt +test
