name: CI

on:
  pull_request:
  push:
    branches: [ main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-10.14]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout current branch (full)
      uses: actions/checkout@v2
    - name: Setup Java and Scala
      uses: olafurpg/setup-scala@v10
    - name: Setup (Linux)
      if: matrix.os == 'ubuntu-18.04'
      env:
        TF_DIR: ~/tensorflow

      run: |
        curl -fsSL https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-2.5.0.tar.gz \
          -o ~/libtensorflow.tar.gz
        mkdir -p {{ env.TF_DIR }} && tar -xzf ~/libtensorflow.tar.gz -C {{ env.TF_DIR }}
        echo "ls HOME"
        ls $HOME
        echo "ls -R ~/tensorflow"
        ls -R {{ env.TF_DIR }}
        # sudo mkdir -p /usr/local && curl -v -fsSL \
        #   https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-2.5.0.tar.gz \
        #   | tar -xzv -C /usr/local
        # ldconfig
        echo "LIBRARY_PATH=~/tensorflow/lib" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=~/tensorflow/lib" >> $GITHUB_ENV
        echo "C_INCLUDE_PATH=~/tensorflow/include" >> $GITHUB_ENV
    - name: Setup (OS X)
      if: matrix.os == 'macos-10.14'
      run: brew install libtensorflow
    - name: Run tests
      run: sbt +test
