name: CI

on:
  pull_request:
  push:
    branches: [ main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-10.14]
        java: [ '1.8', '11', '17' ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout current branch (full)
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v2
    - name: Setup (Linux)
      if: matrix.os == 'ubuntu-18.04'
      run: |
        curl -fsSL https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-2.7.0.tar.gz \
          -o ~/libtensorflow.tar.gz
        mkdir -p ~/tensorflow && tar -xzf ~/libtensorflow.tar.gz -C ~/tensorflow
    - name: Setup (macOS)
      if: matrix.os == 'macos-10.14'
      run: brew install libtensorflow
    - name: Run tests (Linux)
      if: matrix.os == 'ubuntu-18.04'
      with:
          java-version: ${{ matrix.java }}
      run: |
        export LIBRARY_PATH=$LIBRARY_PATH:~/tensorflow/lib
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/tensorflow/lib
        export C_INCLUDE_PATH=$C_INCLUDE_PATH:~/tensorflow/include
        sbt +test
    - name: Run tests (macOS)
      if: matrix.os == 'macos-10.14'
      with:
          java-version: ${{ matrix.java }}
      run: sbt +test
