name: CI

on:
  pull_request:
  push:
    branches: [ main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-11]
        java: [ '11', '17' ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout current branch (full)
      uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
          cache: 'sbt'
    - name: Setup (Linux)
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        curl -fsSL https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-2.10.0.tar.gz \
          -o ~/libtensorflow.tar.gz
        mkdir -p ~/tensorflow && tar -xzf ~/libtensorflow.tar.gz -C ~/tensorflow
    - name: Setup (macOS)
      if: startsWith(matrix.os, 'macos')
      run: brew install libtensorflow
    - name: Run tests (Linux) Java ${{ matrix.java }}
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        export LIBRARY_PATH=$LIBRARY_PATH:~/tensorflow/lib
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/tensorflow/lib
        export C_INCLUDE_PATH=$C_INCLUDE_PATH:~/tensorflow/include
        sbt +test
    - name: Run tests (macOS) Java ${{ matrix.java }}
      if: startsWith(matrix.os, 'macos')
      run: sbt +test
